import React, { useState, useMemo, useEffect } from 'react';
import { Person, Unit, RoleDefinition } from '../types';
import { Users, UserPlus, Briefcase, Home, Edit2, X, Lock, Power, UserX, UserCheck } from 'lucide-react';
import { storageService } from '../services/storageService';

interface PeopleProps {
  people: Person[];
  units: Unit[];
  onAddPerson: (person: Person) => void;
  onUpdatePerson: (person: Person) => void;
  onToggleActive: (id: string, active: boolean) => void;
  onResetPassword: (id: string) => void;
}

export const People: React.FC<PeopleProps> = ({ people, units, onAddPerson, onUpdatePerson, onToggleActive, onResetPassword }) => {
  const [activeTab, setActiveTab] = useState<'RESIDENT' | 'STAFF'>('RESIDENT');
  const [roles, setRoles] = useState<RoleDefinition[]>([]);

  // Form State
  const [editingPersonId, setEditingPersonId] = useState<string | null>(null);
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [roleId, setRoleId] = useState('');
  const [username, setUsername] = useState('');

  // Unit Selection State
  const [selectedBlock, setSelectedBlock] = useState('');
  const [unitId, setUnitId] = useState('');

  useEffect(() => {
    loadRoles();
  }, []);

  const loadRoles = async () => {
    try {
      if ('getRoles' in storageService) {
        const data = await (storageService as any).getRoles();
        setRoles(data);
        // Set default role to first resident role if available
        const residentRole = data.find((r: RoleDefinition) => r.name === 'MORADOR' || r.name === 'RESIDENT');
        if (residentRole) setRoleId(residentRole.id);
      }
    } catch (err) {
      console.error('Erro ao carregar perfis:', err);
    }
  };

  const handleEdit = (person: Person) => {
    setEditingPersonId(person.id);
    setName(person.name);
    setEmail(person.email);
    setPhone(person.phone);
    setRoleId(person.roleId);
    setUsername(person.username || '');

    if (person.unitId) {
      const unit = units.find(u => u.id === person.unitId);
      if (unit) {
        setSelectedBlock(unit.block);
        setUnitId(unit.id);
      }
    } else {
      setSelectedBlock('');
      setUnitId('');
    }

    // Switch tab if needed
    const personRole = roles.find(r => r.id === person.roleId);
    const isResident = personRole?.name === 'MORADOR' || personRole?.name === 'RESIDENT';
    if (isResident && activeTab !== 'RESIDENT') setActiveTab('RESIDENT');
    if (!isResident && activeTab !== 'STAFF') setActiveTab('STAFF');
  };

  const handleCancelEdit = () => {
    setEditingPersonId(null);
    setName('');
    setEmail('');
    setPhone('');
    setUsername('');
    setUnitId('');
    setSelectedBlock('');

    // Reset role to default for current tab
    if (activeTab === 'RESIDENT') {
      const residentRole = roles.find(r => r.name === 'MORADOR' || r.name === 'RESIDENT');
      if (residentRole) setRoleId(residentRole.id);
    } else {
      setRoleId('');
    }
  };

  const handleSubmit = async () => {
    console.log('Tentando salvar pessoa:', { name, email, roleId, unitId, selectedBlock, editingPersonId });

    if (!name || !email || !roleId) {
      alert("Por favor, preencha todos os campos obrigatórios (Nome, Email, Perfil).");
      return;
    }

    if (activeTab === 'RESIDENT' && !unitId) {
      alert("Para moradores, é necessário selecionar uma unidade.");
      return;
    }

    // Check for duplicate username if creating new staff or updating username
    if (activeTab === 'STAFF' && username) {
      const existingUser = people.find(p => p.username === username && p.id !== editingPersonId);
      if (existingUser) {
        alert(`O login de acesso "${username}" já está em uso por outro usuário. Por favor, escolha outro.`);
        return;
      }
    }

    try {
      const selectedRole = roles.find(r => r.id === roleId);
      const personData: Person = {
        id: editingPersonId || '', // ID will be generated by DB if empty
        name,
        email,
        phone,
        roleId,
        roleName: selectedRole?.name,
        unitId: (selectedRole?.name === 'MORADOR' || selectedRole?.name === 'RESIDENT') ? unitId : undefined,
        avatarUrl: `https://ui-avatars.com/api/?name=${name}&background=random`,
        username: (activeTab !== 'RESIDENT' && username) ? username : undefined,
        password: (activeTab !== 'RESIDENT' && !editingPersonId) ? '123' : undefined, // Default password for new staff
        mustChangePassword: (activeTab !== 'RESIDENT' && !editingPersonId) ? true : undefined
      };

      if (editingPersonId) {
        console.log('Atualizando pessoa:', personData);
        await onUpdatePerson(personData);
        alert("Dados atualizados com sucesso!");
        handleCancelEdit();
      } else {
        console.log('Cadastrando nova pessoa:', personData);
        await onAddPerson(personData);
        alert("Pessoa cadastrada com sucesso!");
        handleCancelEdit(); // Reset form
      }

    } catch (error) {
      console.error("Erro ao salvar pessoa:", error);
      alert("Erro ao salvar. Verifique o console para mais detalhes.");
    }
  };

  const filteredPeople = people.filter(p => {
    const personRole = roles.find(r => r.id === p.roleId);
    const isResident = personRole?.name === 'MORADOR' || personRole?.name === 'RESIDENT';

    if (activeTab === 'RESIDENT') return isResident;
    return !isResident && personRole?.name !== 'VISITOR';
  });

  // Get unique blocks
  const uniqueBlocks = useMemo(() => {
    return Array.from(new Set(units.map(u => u.block))).sort();
  }, [units]);

  // Filter units by selected block
  const availableUnits = useMemo(() => {
    if (!selectedBlock) return [];
    return units
      .filter(u => u.block === selectedBlock)
      .sort((a, b) => parseInt(a.number) - parseInt(b.number));
  }, [units, selectedBlock]);

  // Filter roles for dropdown
  const residentRoles = roles.filter(r => r.name === 'MORADOR' || r.name === 'RESIDENT');
  const staffRoles = roles.filter(r => r.name !== 'MORADOR' && r.name !== 'RESIDENT' && r.name !== 'VISITOR');

  const currentEditingPerson = people.find(p => p.id === editingPersonId);

  const hasChanges = useMemo(() => {
    if (!editingPersonId || !currentEditingPerson) return false;

    return (
      name !== currentEditingPerson.name ||
      email !== currentEditingPerson.email ||
      phone !== currentEditingPerson.phone ||
      roleId !== currentEditingPerson.roleId ||
      (activeTab === 'RESIDENT'
        ? unitId !== (currentEditingPerson.unitId || '')
        : username !== (currentEditingPerson.username || ''))
    );
  }, [editingPersonId, currentEditingPerson, name, email, phone, roleId, unitId, username, activeTab]);

  return (
    <div className="space-y-6">

      {/* Tabs */}
      <div className="flex space-x-4 border-b border-slate-200">
        <button
          onClick={() => {
            setActiveTab('RESIDENT');
            handleCancelEdit(); // Reset form when switching tabs
            // Try to find MORADOR or RESIDENT
            const residentRole = roles.find(r => r.name === 'MORADOR' || r.name === 'RESIDENT');
            if (residentRole) {
              setRoleId(residentRole.id);
            } else {
              console.warn('Perfil de MORADOR não encontrado nos roles:', roles);
            }
          }}
          className={`pb-3 px-4 text-sm font-medium transition-colors border-b-2 flex items-center gap-2 ${activeTab === 'RESIDENT'
            ? 'border-blue-600 text-blue-600'
            : 'border-transparent text-slate-500 hover:text-slate-700'
            }`}
        >
          <Home size={16} />
          Moradores
        </button>
        <button
          onClick={() => {
            setActiveTab('STAFF');
            handleCancelEdit(); // Reset form when switching tabs
            // Reset roleId so user must select one
            setRoleId('');
          }}
          className={`pb-3 px-4 text-sm font-medium transition-colors border-b-2 flex items-center gap-2 ${activeTab === 'STAFF'
            ? 'border-blue-600 text-blue-600'
            : 'border-transparent text-slate-500 hover:text-slate-700'
            }`}
        >
          <Briefcase size={16} />
          Funcionários e Admins
        </button>
      </div>

      <div className="flex flex-col lg:flex-row gap-6">
        {/* Form */}
        <div className={`bg-white p-6 rounded-2xl shadow-sm border ${editingPersonId ? 'border-blue-200 ring-2 ring-blue-100' : 'border-slate-100'} flex-1 max-w-md h-fit transition-all`}>
          <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center justify-between">
            <span className="flex items-center">
              {editingPersonId ? <Edit2 className="mr-2 text-blue-600" size={20} /> : <UserPlus className="mr-2 text-blue-600" size={20} />}
              {editingPersonId ? 'Editar Cadastro' : (activeTab === 'RESIDENT' ? 'Novo Morador' : 'Novo Profissional')}
            </span>
            {editingPersonId && (
              <button onClick={handleCancelEdit} className="text-slate-400 hover:text-slate-600" title="Cancelar Edição">
                <X size={20} />
              </button>
            )}
          </h3>

          <div className="space-y-4">
            <div>
              <label className="block text-xs font-semibold text-slate-500 uppercase mb-1">Nome Completo</label>
              <input type="text" value={name} onChange={e => setName(e.target.value)} className="w-full border rounded-lg p-2" />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-500 uppercase mb-1">Email</label>
              <input type="email" value={email} onChange={e => setEmail(e.target.value)} className="w-full border rounded-lg p-2" />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-500 uppercase mb-1">Telefone</label>
              <input type="tel" value={phone} onChange={e => setPhone(e.target.value)} className="w-full border rounded-lg p-2" />
            </div>

            {activeTab === 'RESIDENT' ? (
              <div>
                <label className="block text-xs font-semibold text-slate-500 uppercase mb-1">Perfil</label>
                <select value={roleId} onChange={e => setRoleId(e.target.value)} className="w-full border rounded-lg p-2 bg-white">
                  <option value="">Selecione...</option>
                  {residentRoles.map(r => (
                    <option key={r.id} value={r.id}>{r.name} {r.description && `- ${r.description}`}</option>
                  ))}
                </select>
              </div>
            ) : (
              <>
                <div>
                  <label className="block text-xs font-semibold text-slate-500 uppercase mb-1">Perfil</label>
                  <select value={roleId} onChange={e => setRoleId(e.target.value)} className="w-full border rounded-lg p-2 bg-white">
                    <option value="">Selecione...</option>
                    {staffRoles.map(r => (
                      <option key={r.id} value={r.id}>{r.name} {r.description && `- ${r.description}`}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-500 uppercase mb-1">Login de Acesso</label>
                  <input
                    type="text"
                    value={username}
                    onChange={e => setUsername(e.target.value.toUpperCase())}
                    className="w-full border rounded-lg p-2"
                    placeholder="Ex: JOAO.SILVA"
                  />
                  <p className="text-xs text-slate-400 mt-1">Senha inicial padrão: 123</p>
                </div>
              </>
            )}

            {activeTab === 'RESIDENT' && (
              <>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-semibold text-slate-500 uppercase mb-1">Bloco</label>
                    <select
                      value={selectedBlock}
                      onChange={e => {
                        setSelectedBlock(e.target.value);
                        setUnitId(''); // Reset unit when block changes
                      }}
                      className="w-full border rounded-lg p-2 bg-white"
                    >
                      <option value="">Selecione...</option>
                      {uniqueBlocks.map(block => (
                        <option key={block} value={block}>{block}</option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-500 uppercase mb-1">Apartamento</label>
                    <select
                      value={unitId}
                      onChange={e => setUnitId(e.target.value)}
                      className="w-full border rounded-lg p-2 bg-white disabled:bg-slate-100 disabled:text-slate-400"
                      disabled={!selectedBlock}
                    >
                      <option value="">Selecione...</option>
                      {availableUnits.map(u => (
                        <option key={u.id} value={u.id}>{u.number} ({u.floor}º)</option>
                      ))}
                    </select>
                  </div>
                </div>
              </>
            )}

            {/* Account Actions for Staff */}
            {editingPersonId && activeTab === 'STAFF' && currentEditingPerson && (
              <div className="mt-6 pt-6 border-t border-slate-100">
                <h4 className="text-sm font-bold text-slate-700 mb-3 flex items-center gap-2">
                  <Lock size={16} />
                  Segurança e Acesso
                </h4>
                <div className="space-y-3">
                  <button
                    onClick={() => {
                      if (confirm('Tem certeza que deseja resetar a senha deste usuário?')) {
                        onResetPassword(editingPersonId);
                      }
                    }}
                    className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-amber-50 text-amber-700 rounded-lg hover:bg-amber-100 transition-colors border border-amber-200 text-sm font-medium"
                  >
                    <Lock size={16} />
                    Resetar Senha
                  </button>

                  <button
                    onClick={() => {
                      const isActive = currentEditingPerson.active !== false;
                      const action = isActive ? 'inativar' : 'ativar';
                      console.log(`User clicked ${action} for ${editingPersonId}. Current active status: ${currentEditingPerson.active}`);

                      if (confirm(`Tem certeza que deseja ${action} este usuário?`)) {
                        onToggleActive(editingPersonId, !isActive);
                      }
                    }}
                    className={`w-full flex items-center justify-center gap-2 px-4 py-2 rounded-lg transition-colors border text-sm font-medium ${currentEditingPerson.active !== false
                      ? 'bg-red-50 text-red-700 hover:bg-red-100 border-red-200'
                      : 'bg-green-50 text-green-700 hover:bg-green-100 border-green-200'
                      }`}
                  >
                    {currentEditingPerson.active !== false ? <UserX size={16} /> : <UserCheck size={16} />}
                    {currentEditingPerson.active !== false ? 'Inativar Usuário' : 'Ativar Usuário'}
                  </button>
                </div>
              </div>
            )}

            <div className="flex gap-2 mt-4 pt-4 border-t border-slate-100">
              <button
                onClick={handleSubmit}
                disabled={editingPersonId ? !hasChanges : false}
                className={`flex-1 font-medium py-2 rounded-lg transition-colors ${editingPersonId
                    ? (hasChanges ? 'bg-green-600 hover:bg-green-700 text-white' : 'bg-slate-300 text-slate-500 cursor-not-allowed')
                    : 'bg-blue-600 hover:bg-blue-700 text-white'
                  }`}
              >
                {editingPersonId ? 'Salvar Alterações' : 'Cadastrar'}
              </button>

              {editingPersonId && (
                <button
                  onClick={handleCancelEdit}
                  className="px-4 py-2 bg-slate-200 text-slate-700 rounded-lg hover:bg-slate-300 transition-colors"
                >
                  Cancelar
                </button>
              )}
            </div>
          </div>
        </div>

        {/* List */}
        <div className="flex-1 bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
          <h3 className="text-lg font-bold text-slate-800 mb-4">Diretório ({filteredPeople.length})</h3>
          <div className="overflow-y-auto max-h-[500px]">
            <table className="min-w-full divide-y divide-slate-200">
              <thead className="bg-slate-50">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase">Nome</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase">Contato</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase">
                    {activeTab === 'RESIDENT' ? 'Unidade' : 'Perfil'}
                  </th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase">Ações</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-slate-100">
                {filteredPeople.map(p => {
                  const personRole = roles.find(r => r.id === p.roleId);
                  return (
                    <tr key={p.id} className={`hover:bg-slate-50 ${editingPersonId === p.id ? 'bg-blue-50' : ''} ${p.active === false ? 'opacity-60 bg-slate-50' : ''}`}>
                      <td className="px-4 py-3 whitespace-nowrap">
                        <div className="flex items-center">
                          <img className={`h-8 w-8 rounded-full mr-3 ${p.active === false ? 'grayscale' : ''}`} src={p.avatarUrl} alt="" />
                          <div>
                            <div className="text-sm font-medium text-slate-900 flex items-center gap-2">
                              {p.name}
                              {p.active === false && (
                                <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-red-100 text-red-600 uppercase">
                                  Inativo
                                </span>
                              )}
                            </div>
                          </div>
                        </div>
                      </td>
                      <td className="px-4 py-3 whitespace-nowrap">
                        <div className="text-sm text-slate-500">{p.email}</div>
                        <div className="text-xs text-slate-400">{p.phone}</div>
                      </td>
                      <td className="px-4 py-3 whitespace-nowrap">
                        {(personRole?.name === 'MORADOR' || personRole?.name === 'RESIDENT') ? (
                          <span className="text-sm text-slate-700 font-medium">
                            {units.find(u => u.id === p.unitId)?.number
                              ? `Bl ${units.find(u => u.id === p.unitId)?.block} - ${units.find(u => u.id === p.unitId)?.number}`
                              : 'N/A'}
                          </span>
                        ) : (
                          <span className={`px-2 py-1 text-xs rounded-full font-medium ${personRole?.name === 'ADMIN' ? 'bg-purple-100 text-purple-700' : 'bg-blue-100 text-blue-700'}`}>
                            {personRole?.name || 'N/A'}
                          </span>
                        )}
                      </td>
                      <td className="px-4 py-3 whitespace-nowrap text-right">
                        <button
                          onClick={() => handleEdit(p)}
                          className="text-blue-600 hover:text-blue-800 p-1 rounded hover:bg-blue-50 transition-colors"
                          title="Editar"
                        >
                          <Edit2 size={16} />
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  );
};