import React, { useState, useEffect } from 'react';
import { Shield, Plus, Trash2, AlertCircle } from 'lucide-react';
import { storageService } from '../services/storageService';
import { RoleDefinition } from '../types';

export const RoleManagement: React.FC = () => {
    const [roles, setRoles] = useState<RoleDefinition[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [showAddForm, setShowAddForm] = useState(false);
    const [newRole, setNewRole] = useState({ name: '', description: '' });

    useEffect(() => {
        loadRoles();
    }, []);

    const loadRoles = async () => {
        try {
            setIsLoading(true);
            if ('getRoles' in storageService) {
                const data = await (storageService as any).getRoles();
                setRoles(data);
            } else {
                setError("O serviço de armazenamento atual não suporta gerenciamento de perfis.");
            }
        } catch (err) {
            console.error(err);
            setError("Erro ao carregar perfis.");
        } finally {
            setIsLoading(false);
        }
    };

    const handleAddRole = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!newRole.name.trim()) {
            alert("Nome do perfil é obrigatório");
            return;
        }

        try {
            if ('addRole' in storageService && 'initRolePermissions' in storageService) {
                // Add role
                const roleToAdd: RoleDefinition = {
                    id: '', // Will be generated by DB
                    name: newRole.name.toUpperCase().replace(/\s+/g, '_'),
                    description: newRole.description
                };

                await (storageService as any).addRole(roleToAdd);

                // Reload to get the new role with ID
                await loadRoles();

                // Get the newly created role
                const roles = await (storageService as any).getRoles();
                const createdRole = roles.find((r: RoleDefinition) => r.name === roleToAdd.name);

                if (createdRole) {
                    // Initialize permissions for the new role
                    await (storageService as any).initRolePermissions(createdRole.id);
                }

                setNewRole({ name: '', description: '' });
                setShowAddForm(false);
            }
        } catch (err: any) {
            console.error(err);
            alert(`Erro ao adicionar perfil: ${err.message || 'Erro desconhecido'}`);
        }
    };

    const handleDeleteRole = async (id: string, name: string) => {
        if (!confirm(`Tem certeza que deseja excluir o perfil "${name}"? Isso também removerá todas as permissões associadas.`)) {
            return;
        }

        try {
            if ('deleteRole' in storageService) {
                await (storageService as any).deleteRole(id);
                await loadRoles();
            }
        } catch (err: any) {
            console.error(err);
            alert(`Erro ao excluir perfil: ${err.message || 'Erro desconhecido'}`);
        }
    };

    if (isLoading) return <div className="p-8 text-center">Carregando perfis...</div>;
    if (error) return <div className="p-8 text-center text-red-600 flex items-center justify-center gap-2"><AlertCircle size={20} /> {error}</div>;

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h3 className="text-lg font-semibold text-slate-700 flex items-center gap-2">
                    <Shield size={20} className="text-blue-600" />
                    Gerenciamento de Perfis de Usuário
                </h3>
                <button
                    onClick={() => setShowAddForm(!showAddForm)}
                    className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                >
                    <Plus size={18} />
                    Novo Perfil
                </button>
            </div>

            {showAddForm && (
                <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
                    <h4 className="font-semibold text-slate-800 mb-4">Adicionar Novo Perfil</h4>
                    <form onSubmit={handleAddRole} className="space-y-4">
                        <div>
                            <label className="block text-sm font-medium text-slate-700 mb-1">
                                Nome do Perfil *
                            </label>
                            <input
                                type="text"
                                value={newRole.name}
                                onChange={(e) => setNewRole({ ...newRole, name: e.target.value })}
                                placeholder="Ex: GERENTE, PORTEIRO, etc."
                                className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                required
                            />
                            <p className="text-xs text-slate-500 mt-1">
                                O nome será convertido para maiúsculas e espaços serão substituídos por underscores
                            </p>
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-slate-700 mb-1">
                                Descrição
                            </label>
                            <input
                                type="text"
                                value={newRole.description}
                                onChange={(e) => setNewRole({ ...newRole, description: e.target.value })}
                                placeholder="Ex: Gerente do condomínio"
                                className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                            />
                        </div>
                        <div className="flex gap-2">
                            <button
                                type="submit"
                                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                            >
                                Adicionar
                            </button>
                            <button
                                type="button"
                                onClick={() => {
                                    setShowAddForm(false);
                                    setNewRole({ name: '', description: '' });
                                }}
                                className="px-4 py-2 bg-slate-200 text-slate-700 rounded-lg hover:bg-slate-300 transition-colors"
                            >
                                Cancelar
                            </button>
                        </div>
                    </form>
                </div>
            )}

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {roles.map(role => (
                    <div key={role.id} className="bg-white p-6 rounded-xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
                        <div className="flex justify-between items-start mb-3">
                            <div className="flex-1">
                                <h4 className="font-bold text-slate-800 text-lg">{role.name}</h4>
                                {role.description && (
                                    <p className="text-sm text-slate-500 mt-1">{role.description}</p>
                                )}
                            </div>
                            <button
                                onClick={() => handleDeleteRole(role.id, role.name)}
                                className="text-red-500 hover:text-red-700 hover:bg-red-50 p-2 rounded-lg transition-colors"
                                title="Excluir perfil"
                            >
                                <Trash2 size={18} />
                            </button>
                        </div>
                        <div className="text-xs text-slate-400 border-t pt-3">
                            ID: {role.id.substring(0, 8)}...
                        </div>
                    </div>
                ))}
            </div>

            {roles.length === 0 && (
                <div className="text-center py-12 text-slate-500">
                    <Shield size={48} className="mx-auto mb-4 text-slate-300" />
                    <p>Nenhum perfil cadastrado ainda.</p>
                    <p className="text-sm">Clique em "Novo Perfil" para começar.</p>
                </div>
            )}
        </div>
    );
};
